apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Traefik IngressRoute CRD 는 kustomize 가 기본적으로 네임스페이스를 주입하지 않으므로
# metadata.namespace 를 명시합니다.
namespace: auth

resources:
  - ../default
  - ingressroute.yaml
